"""
Django settings for Projeto_Apostas project.

Generated by 'django-admin startproject' using Django 5.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/



ALLOWED_HOSTS = ['127.0.0.1', 'nbabestprops.ngrok.app']  

CSRF_TRUSTED_ORIGINS = ['https://nbabestprops.ngrok.app']

LOGIN_URL = '/login/'


# Application definition

INSTALLED_APPS = [
    'daphne',  # WebSocket support - deve estar no topo
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'channels',  # Django Channels
    'Projeto_Apostas_App',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
]

ROOT_URLCONF = 'Projeto_Apostas.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Projeto_Apostas.wsgi.application'
ASGI_APPLICATION = 'Projeto_Apostas.asgi.application'

from dotenv import load_dotenv

load_dotenv()  

import dj_database_url

#DATABASES = {
#    'default': dj_database_url.config(
#        default='postgresql://nbapropsdb_user:XHphF4NeHqJLEMmz3jd2EdX1X8GDXiQn@dpg-d0h9hh24d50c73bb1a40-a:5432/nbapropsdb',
#        conn_max_age=600,
#        ssl_require=True
#    )
#}


SECRET_KEY = os.getenv('DJANGO_SECRET_KEY')
if not SECRET_KEY:
    raise ValueError("A variável de ambiente DJANGO_SECRET_KEY não está definida!")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': os.getenv('DB_NAME'),
        'USER': os.getenv('DB_USER'),
        'PASSWORD': os.getenv('DB_PASSWORD'),
        'HOST': os.getenv('DB_HOST'),
        'PORT': '5432',
    }
}




# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Define um modelo de utilizador personalizado para o Django usar, em vez do modelo padrão.
AUTH_USER_MODEL = 'Projeto_Apostas_App.Utilizadores'


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

# Diretório onde os arquivos estáticos serão coletados após o comando collectstatic
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# URL para acessar os arquivos estáticos
STATIC_URL = '/static/'

# Para que os arquivos estáticos sejam servidos corretamente em produção
STATICFILES_STORAGE = 'django.contrib.staticfiles.storage.StaticFilesStorage'



# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Configuração para arquivos de mídia
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Configurações de Proxy
PROXY_ENABLED = os.getenv('PROXY_ENABLED', 'False').lower() == 'true'
PROXY_URL = os.getenv('PROXY_URL', '')
PROXY_USERNAME = os.getenv('PROXY_USERNAME', '')
PROXY_PASSWORD = os.getenv('PROXY_PASSWORD', '')

# Configuração de timeout para requisições
REQUEST_TIMEOUT = int(os.getenv('REQUEST_TIMEOUT', '30'))

# ============================================
# CONFIGURAÇÕES WEBSOCKET E REAL-TIME
# ============================================

# Channels Layer - usando Redis como backend
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            "hosts": [(os.getenv('REDIS_HOST', '127.0.0.1'), int(os.getenv('REDIS_PORT', '6379')))],
        },
    },
}

# ============================================
# CONFIGURAÇÕES MONGODB - CACHE NBA DATA
# ============================================

# Conexão MongoDB
MONGODB_SETTINGS = {
    'host': os.getenv('MONGODB_HOST', 'localhost'),
    'port': int(os.getenv('MONGODB_PORT', '27017')),
    'db': os.getenv('MONGODB_DB', 'nba_cache'),
    'username': os.getenv('MONGODB_USER', ''),
    'password': os.getenv('MONGODB_PASSWORD', ''),
}

# Construir MongoDB URI
if MONGODB_SETTINGS['username'] and MONGODB_SETTINGS['password']:
    MONGODB_URI = f"mongodb://{MONGODB_SETTINGS['username']}:{MONGODB_SETTINGS['password']}@{MONGODB_SETTINGS['host']}:{MONGODB_SETTINGS['port']}/{MONGODB_SETTINGS['db']}"
else:
    MONGODB_URI = f"mongodb://{MONGODB_SETTINGS['host']}:{MONGODB_SETTINGS['port']}/{MONGODB_SETTINGS['db']}"

# Cache settings - TTL em segundos
NBA_CACHE_SETTINGS = {
    'PLAYER_STATS_TTL': 300,  # 5 minutos
    'LIVE_GAMES_TTL': 10,  # 10 segundos para jogos ao vivo
    'PLAYER_INFO_TTL': 3600,  # 1 hora
    'TEAM_INFO_TTL': 3600,  # 1 hora
    'GAME_SCHEDULE_TTL': 600,  # 10 minutos
}

